<?php
/** @var Skybox_International_Helper_Data $_helper */
$_helper = Mage::helper('skyboxinternational/data');

if ($_helper->getActive()) {

    /** @var Skybox_Core_Model_Config $_config */
    $_config = Mage::getModel('skyboxcore/config');

    /** @var Skybox_Checkout_Model_Api_Checkout $_checkout */
    $_checkout = Mage::getModel('skyboxcheckout/api_checkout');

    /** @var Skybox_Core_Helper_Allow $allowHelper */
    $allowHelper = Mage::helper('skyboxcore/allow');

    $isCartEnabled = $allowHelper->isCartBarEnabled();

    $_cartDataURL = "";
    $_merchant = $_helper->getMerchantCode();
    $template = "";
    $cartId = $_helper->getCartId();

    $_checkout->InitializeBarSkybox();

    $change_country = false;

    $request = $this->getRequest();
    $module = $request->getModuleName();
    $controller = $request->getControllerName();
    $action = $request->getActionName();
    $getHomeUrl = Mage::helper('core/url')->getHomeUrl();
    $urlCheckCart = Mage::getUrl("checkout/cart");

    $cart = $_config->getSession()->getCartSkybox();

    // Load CSS & JS
    $skybox_url = $_helper->getSkyboxUrlMain();// $_config->skyboxDefaultUrl;
    $api_css_button_international = $skybox_url . 'widgets/api-button/css/api-button-international-css.ashx';
    $api_css_button_international .= '?s=' . $_helper->getMerchantCode();
    $api_css_button_international .= '&CssVersion=' . $_helper->getCssVersion();
    $api_js_button_international = $skybox_url . 'Content/debug/API/js/api-button-tooltip.js';
    $countryChange = 0;

    if ($allowHelper->isCartBarEnabled()) :
        $countryChange = 1;
        $template = '';
        $cart = $_config->getSession()->getCartSkybox();
        if (!empty($cart)) :
            $template = $cart->BarHtmlTemplate;
            foreach ($cart as $key => $value) :
                $template = str_replace('{' . $key . '}', $value, $template);
            endforeach;
        endif;
        $_cartDataURL = $cart->CartDataURL;
        echo $template;
    endif;

    if ($allowHelper->isChangeCountryEnabled()):
        $cart = $_config->getSession()->getCartSkybox();
        $template = "<div class='main-container' style='padding: 10px 0 0;text-align: right;'>";
        $template .= "<div class='change_country'>";
        $template .= "<a class='skx_position_option_country' href='javascript:;'>Change country</a>";
        $template .= "</div>";
        $template .= "</div>";
        $change_country = true;
        $countryChange = 0;
        $_cartDataURL = $cart->CartDataURL;
        echo $template;
    endif;

    if ($allowHelper->isPriceEnabled()) {
        $productConfigurable = $this->getSkinUrl('js/skybox/catalog.product.configurable.js');
        echo '<script type="text/javascript" src="' . $productConfigurable . '"></script>';
    }

    $skyBoxUrlClientBase = $_helper->getSkyBoxUrlAPI();
    $storeCode = Mage::getModel('skyboxcatalog/api_product')->getStoreCode();
    $skyBoxUrlClientGet = str_replace("apirest/", "", $skyBoxUrlClientBase);
    $skyBoxUrlClient = $skyBoxUrlClientGet . "multiplecalculate/" . $storeCode . "/calc-";
    $skyboxForceReload = intval(Mage::getBlockSingleton('page/html_header')->getIsHomePage());
    ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $api_css_button_international; ?>"/>
    <link rel="stylesheet" type="text/css"
          href="<?php echo $this->getSkinUrl('css/skybox/style.css?v=' . $_helper->getCssVersion()); ?>"/>
    <script type="text/javascript">
        var URL_CHECK_CART = "<?php echo $urlCheckCart ?>";
        var CART_ID = "<?php echo $cartId ?>";
        var CART_DATA_URL_SKYBOX = "<?php echo $_cartDataURL ?>";
        var MERCHANT_ID_SKYBOX = "<?php echo $_merchant ?>";
        var SKYBOX_URL = "<?php echo $skybox_url ?>";
        var CHANGE_COUNTRY = "<?php echo $change_country ?>";
        var ACTUAL_URI = "<?php echo 'http://' . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . $_SERVER['REQUEST_URI'] ?>";
        var GET_HOME_URL = "<?php echo $getHomeUrl ?>";
        var COUNTRY_CHANGE = "<?php echo $countryChange?>";
        var IS_SKYBOX_VISIBLE = "<?php echo $_checkout->getLocationAllow(); ?>";
        var URL_BASE_MAGENTO = "<?php echo Mage::getBaseUrl() ?>";
        var IS_REGISTRATION_DISABLED_SKYBOX = 1;
        var SKYBOX_FORCE_RELOAD = "<?php echo $skyboxForceReload; ?>";
        var LOADING_IMAGE = "<?php echo $this->getSkinUrl('images/skybox/ajax-loading.gif')?>";

        (function ($) {
            $(document).ready(function () {
                if (typeof $.fancybox != "function") {
                    var fileref = document.createElement("link");
                    fileref.rel = "stylesheet";
                    fileref.type = "text/css";
                    fileref.href = "<?php echo $this->getSkinUrl('css/skybox/jquery.fancybox.css');?>";
                    document.getElementsByTagName("head")[0].appendChild(fileref);
                    $('head').append($('<script />').attr('src', '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'js/skybox/jquery.fancybox.js'; ?>'));
                }
                $(".skybox-price-set").each(function (index) {
                    var SkyBoxUrlClient = "<?php echo $skyBoxUrlClient;?>";
                    var dataId = $(this).attr("id");
                    var id = $(this).attr("product-id");
                    var url = SkyBoxUrlClient + id + ".html";
                    // console.log("URL : " + url);
                    var content = $.get(url, function (data) {
                        $("#" + dataId).html(data);
                    });
                });
            });
        })(jQuery);
    </script>
    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'js/skybox/main.js'; ?>"></script>
    <script type="text/javascript">
        //<![CDATA[
        var SKYBOX_OPTIONS_PRICE_URL = '<?php echo Mage::getUrl(); ?>skbcheckout/calculate';
        //]]>
    </script>
    <script type="text/javascript" src="<?php echo $api_js_button_international; ?>"></script>
    <?php
    // note: Just to force reload page on Home Page.
    $forceReload = $_config->getSession()->getChangeCountryHomePage();
    $forceReload = isset($forceReload) ? $forceReload : 0;

    if (Mage::getBlockSingleton('page/html_header')->getIsHomePage()) :
        if ($forceReload == 1):
            $forceReload = 0;
            $_config->getSession()->setChangeCountryHomePage($forceReload);
            ?>
            <script type="text/javascript">
                //                console.log("[Skybox] Reloading page...");
                window.location.reload(false);
            </script>
            <?php
        endif;
    endif;
    ?>
    <script>
        setTimeout(function () {
            var country_change = "<?php echo $countryChange?>";
            if (parseInt(country_change) === 1) {
                var currencyISO_ = document.getElementsByClassName('skx_banner_label_currencyISO');
                if (currencyISO_.length > 1) {
                    var nextSiblingOne = currencyISO_[0].nextElementSibling;
                    var getAttrNextSiblingOne = nextSiblingOne.getAttribute('class');
                    var nextSiblingLast = currencyISO_[1].nextElementSibling;
                    nextSiblingLast.setAttribute('class', getAttrNextSiblingOne);
                    currencyISO_[1].innerHTML = currencyISO_[0].innerHTML;
                }
            } else {
                var optCountry = document.getElementsByClassName('skx_position_option_country');
                if (optCountry.length > 1) {
                    optCountry[1].innerHTML = optCountry[0].innerText;
                    try {
                        document.getElementById('l_checkout_view_account').style.display = 'none';
                    } catch (e) {

                    }
                }
            }
        }, 500);
    </script>

    <?php
}
?>
