<?php
$_helper = Mage::helper('skyboxinternational/data');

$_model = Mage::getModel('skyboxcore/standard');

/** @var Skybox_Core_Model_Config $_config */
$_config = Mage::getModel('skyboxcore/config');

/** @var Skybox_Checkout_Model_Api_Checkout $_checkout */
$_checkout = Mage::getModel('skyboxcheckout/api_checkout');

/** @var Skybox_Core_Helper_Allow $allowHelper */
$allowHelper = Mage::helper('skyboxcore/allow');

$isCartEnabled = $allowHelper->isCartBarEnabled();

$_cartDataURL = "";
$_merchant = $_helper->getMerchantCode();
$template = "";
$cartId = $_helper->getCartId();

Mage::log("InitializeBarSkybox ", null, 'skyboxcheckout.log', true);
$_checkout->InitializeBarSkybox();

$change_country = false;
$request = $this->getRequest();
$module = $request->getModuleName();
$controller = $request->getControllerName();
$action = $request->getActionName();
$getHomeUrl = Mage::helper('core/url')->getHomeUrl();
$_url_check_cart = Mage::getUrl("checkout/cart");

$cart = $_config->getSession()->getCartSkybox();
/**
 * Start Aditional we add a line debug with integration information
 */
echo '<script>
            console.log("LocationAllowService: ' . $_checkout->getLocationAllow() . ' ");
      </script>';
/**
 * End Aditional we add a line debug with integration information
 */
//$template = "<a href='#' id='link_choise_country'>&nbsp;</a>";
// Load CSS & JS
$skybox_url = $_helper->getSkyboxUrlMain();// $_config->skyboxDefaultUrl;
$api_css_button_international = $skybox_url . 'widgets/api-button/css/api-button-international-css.ashx';
$api_css_button_international .= '?s=' . $_helper->getMerchantCode();
$api_css_button_international .= '&CssVersion=' . $_helper->getCssVersion();
$api_js_button_international = $skybox_url . 'Content/debug/API/js/api-button-tooltip.js';

if ($allowHelper->isCartBarEnabled()) :
    $template = '';
    $cart = $_config->getSession()->getCartSkybox();
    if (!empty($cart)) :
        $template = $cart->BarHtmlTemplate;
        foreach ($cart as $key => $value) :
            $template = str_replace('{' . $key . '}', $value, $template);
        endforeach;
    endif;
    $_cartDataURL = $cart->CartDataURL;
    echo $template;
endif;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $api_css_button_international; ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/skybox/style.css?v=' . $_helper->getCssVersion()); ?>"/>
<!--    <link rel="stylesheet" type="text/css" href="--><?php #echo $this->getSkinUrl('css/skybox/style.css?v=230120171122');?><!--"/>-->
<script type="text/javascript">
    var URL_CHECK_CART  = "<?php echo $_url_check_cart ?>";
    var CART_ID         = "<?php echo $cartId ?>";
    var CART_DATA_URL   = "<?php echo $_cartDataURL ?>";
    var MERCHANT        = "<?php echo $_merchant ?>";
    var SKYBOX_URL      = "<?php echo $skybox_url ?>";
    var CHANGE_COUNTRY  = "<?php echo $change_country ?>";
    var ACTUAL_URI      = "<?php echo 'http://' . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . $_SERVER['REQUEST_URI'] ?>";
    var GET_HOME_URL    = "<?php echo $getHomeUrl ?>";
    jQuery(document).ready(function() {
        jQuery(".skybox-price-set").each(function( index ) {
            <?php
            $skyBoxUrlClientBase= $_helper->getSkyBoxUrlAPI();
            $codeShop           = Mage::getModel('skyboxcatalog/api_product')->getStoreCode();
            $skyBoxUrlClientGet = str_replace("apirest/", "", $skyBoxUrlClientBase);
            $skyBoxUrlClient    = $skyBoxUrlClientGet . "multiplecalculate/" . $codeShop . "/calc-";
            ?>
            var SkyBoxUrlClient = "<?php echo $skyBoxUrlClient;?>";
            var dataId = jQuery(this).attr("id");
            var id = jQuery(this).attr("product-id");
            var url = SkyBoxUrlClient + id + ".html";
            var content = jQuery.get(url, function (data) {
                jQuery("#" + dataId).html(data);
                /*return data;*/
            });
//            console.log("URL SkyBoxUrlClient: " +url);
            //console.log(url);
            /*console.log(content);*/
        });
    });

    (function ($) {

        var widthPage = 0;
        var heightPage = 0;
        var popup = {};
        var popupWidth = 540;
        var popupHeight = 545;
        var win = '';

        function showPopup(name, t, url, w, h) {
            //winCompare = new Window('popup', {className: 'alphacube', title: t, url: url, width: w, height: h, minimizable: false, maximizable: false, showEffectOptions: {duration: 0.4}, hideEffectOptions: {duration: 0.4} });
            winCompare = new Window(name, {
                className: 'alphacube',
                title: t,
                url: url,
                width: w,
                height: h,
                minimizable: false,
                maximizable: false,
                showEffectOptions: {duration: 0.4},
                hideEffectOptions: {duration: 0.4},
                destroyOnClose: true,
                draggable: false,
                resizable: false
            });

            winCompare.setDestroyOnClose();
            winCompare.setZIndex(9999);
            winCompare.showCenter(true);
            return winCompare;
        }

        function goToCart() {
            document.location = URL_CHECK_CART;
        }

        function goToInitializeSession() {
            var idCart      = CART_ID;
            var datos       = CART_DATA_URL;
            var merchant    = MERCHANT;
            var actualUri   = ACTUAL_URI + "?LoadFrame=1";
            var url         = SKYBOX_URL + "WebForms/PublicSite/Tracking.aspx?" + datos + "&merchant=" + merchant + "&idCart=" + idCart + "&ReLoad=1&uri=" + actualUri;
            var name        = 'initSession' + Date.now();
            callAlphacube();
            showPopup(name, '', url, (widthPage - 50 ), ((heightPage < 800) ? heightPage - 50 : 800));
        }

        function callAlphacube(){
            var alphacube_ = document.querySelectorAll('.alphacube_close');
            if(alphacube_.length > 0){
                var overlay_ = document.getElementById("overlay_modal");

                if(overlay_ !== null) overlay_.style.display = '';
                var id_modal = (alphacube_[1]) ? alphacube_[1].parentNode.getAttribute('id') : '';
                try{
                    document.getElementById(id_modal).remove();
                }
                catch(e) {

                }
            }
        }

        function goToLocation() {
            win = 'resync';
            var datos = CART_DATA_URL;
            var process_url = GET_HOME_URL + "skbcheckout/process";
            var return_url = getReturnUrl();
//            var return_url = document.URL;
            var change_country_status = CHANGE_COUNTRY;
            var url = SKYBOX_URL + "Webforms/PublicSite/ReSync.aspx?" + datos;
            url += "&process_url=" + process_url;
            url += "&return_url=" + return_url;
            url += "&change_country=" + change_country_status;

            var _size = getSizeForPopup();
            var name = 'selectLocation' + Date.now();
            callAlphacube();
            popup = showPopup(name, '', url, _size.width, _size.height);
        }

        function goToTrackingLocation() {
            var url = SKYBOX_URL + "Webforms/PublicSite/Tracking.aspx?" + CART_DATA_URL + "&idCart=" + CART_ID;
            var name = 'tracking' + Date.now();
            showPopup(name, '', url, (widthPage - 50 ), ((heightPage < 800) ? heightPage - 50 : 800));
        }

        function loadIframe() {
            var actualUri = ACTUAL_URI;
            var flgLoadIframe = "<?php echo (isset($_GET['LoadFrame'])) ? $_GET['LoadFrame'] : 0; ?>";
            if (flgLoadIframe === "1") {
                if (actualUri.indexOf("skbcheckout/international") === -1) goToInitializeSession();
            }
        }

        var createCookie = function(name, value, days) {
            var expires;
            if (days) {
                var date = new Date();
                date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                expires = "; expires=" + date.toGMTString();
            } else {
                expires = "";
            }
            document.cookie = name + "=" + value + expires + "; path=/";
        };

        function getCookie(c_name) {
            if (document.cookie.length > 0) {
                c_start = document.cookie.indexOf(c_name + "=");
                if (c_start !== -1) {
                    c_start = c_start + c_name.length + 1;
                    c_end = document.cookie.indexOf(";", c_start);
                    if (c_end === -1) {
                        c_end = document.cookie.length;
                    }
                    return unescape(document.cookie.substring(c_start, c_end));
                }
            }
            return "";
        }

        function postMessageIframe() {
            var eventMethod = window.addEventListener ? "addEventListener" : "attachEvent";
            var eventer = window[eventMethod];
            var messageEvent = eventMethod === "attachEvent" ? "onmessage" : "message";
            eventer(messageEvent,function(e) {
//                if(e.origin == 'https://www.skyboxcheckout.com'){
                recalculateHeightIframe(e.data);
//                }
            },false);
        }

        function recalculateHeightIframe(data) {
            if (data.win === 'resync') {
                popupHeight = data.height;
                var _size = getSizeForPopup();
                try{
                    popup.setSize(_size.width, _size.height);
                }
                catch (e) {
//                    console.log("not calculate popup:::: ", e);
                }
//                popup.showCenter(true);
            }
        }
        function recalculateHeight() {
            if(!jQuery.isEmptyObject(popup) && win === 'resync'){
                var iFrameDOM = $("iframe#selectLocation_content").contents();
                popupHeight = iFrameDOM.find("body").height()+30;
                console.log(popupHeight);
                var _size = getSizeForPopup();
                popup.setSize(_size.width, _size.height)
//                popup.updateHeight()s
//                var fh = document.getElementById('selectLocation_content').contentWindow.document.getElementById('form1')
            }
            win = '';
        }

        function browserResize() {
            jQuery(window).resize(function() {
                if(!jQuery.isEmptyObject(popup)){
                    var _size = getSizeForPopup();
                    popup.setSize(_size.width, _size.height)
                }
            });
        }

        function getSizeForPopup() {
            var _width = jQuery(window).width();
            var _height = jQuery(window).height();
            _width  = (_width < popupWidth) ? _width - 30 : popupWidth ;
            return {width: _width, height: popupHeight};
        }

        $(".skx_position_option_country").unbind().click(function(){
            goToLocation();
        });
        $(".skx_banner_image_account").unbind().click(function(){
            goToInitializeSession();
        });

        $(document).ready(function () {
            widthPage = $(window).width();
            heightPage = $(window).height();
            $(".skx_banner_image_car").click(goToCart);
//            $(".skx_position_option_country").click(goToLocation);
//            $(".skx_banner_image_account").click(goToInitializeSession);
            $(".skx_banner_image_tracking").click(goToTrackingLocation);
            $("#link_choise_country").click(goToCart);
            postMessageIframe();
            loadIframe();
            browserResize();

            <?php if(Mage::getBlockSingleton('page/html_header')->getIsHomePage() && $change_country == true) : ?>
            if ( !getCookie('tivoli_latam_homepage') ) {
                createCookie('tivoli_latam_homepage', 1);
                //goToLocation();
            }
            <?php endif; ?>
        });
    })(jQuery);
</script>

<script type="text/javascript">
    //<![CDATA[
    var SKYBOX_OPTIONS_PRICE_URL = '<?php echo Mage::getUrl(); ?>skbcheckout/calculate';
    //]]>
</script>

<script type="text/javascript" src="<?php echo $api_js_button_international; ?>"></script>

<?php

/**
 * Integration 3 start, show bar*
 */
if (!$_checkout->getErrorAuthenticate() && $_checkout->getLocationAllow()) : // Rogged
    // Calculate height
    $size = 0;

    $UserTemporal = "1";
    $CartItemCount = 0;

    if (!$_checkout->getErrorAuthenticate() && $_checkout->getLocationAllow()) :
        $cart = $_config->getSession()->getCartSkybox();
        if (!empty($cart)) :
            $UserTemporal = $cart->{'UserTemporal'};
            $CartItemCount = intval($cart->{'CartItemCount'});
            for ($i = 1; $i <= $CartItemCount; $i++) :
                $size = $size + 50;
            endfor;
        endif;
    endif;


    $merchant = $_helper->getMerchantCode();
    $storeId = $_helper->getStoreId();
    $cartId = $_helper->getCartId();
    $guid = $_model->getGuidApi();
    $urlSuccess = Mage::getUrl("skbcheckout/international/success");
    $urlConfirm = Mage::getUrl("skbcheckout/international");
    $token = $_model->AuthenticateService()->getAuthorizedToken();

    $url = $_helper->getSkyboxUrlMain() . "WebForms/Checkout/APICheckout.aspx"; //$_config->skyboxDefaultUrl . "WebForms/Checkout/APICheckout.aspx";
    $url .= "?token=" . $token;
    $url .= "&GuiId=" . $guid;
    $url .= "&merchant=" . $merchant;
    $url .= "&idCart=" . $cartId;
    $url .= "&idStore=" . $storeId;
    $url .= "&UrlC=" . $urlConfirm;// "http://magento.skynet.com/magento192/skbcheckout/international";
    $url .= "&paypal=" . $_GET["paypal"];
    $url .= '&checkout=' . strip_tags(Mage::app()->getRequest()->getParam('checkout',''));
    $url .= "&UrlR=" . $urlSuccess;

    if($size == 0):
        $cart = Mage::getSingleton('checkout/session')->getQuote();
        foreach ($cart->getAllItems() as $item) :
            $size = $size + 50;
        endforeach;
    endif;

    if($size == 0) $size = 100;

    $height = (($UserTemporal == "1") ? 1400 : 900) + $size;
    $height = 2500;
    ?>
    <iframe id="iframe_skybox_checkout" src="<?php echo $url; ?>" frameborder="0" scrolling="no"></iframe>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            var height = <?php echo $height; ?>;
            var isMobile = /Mobi/.test(navigator.userAgent);
            console.log("isMobile ::: " + isMobile);
            if (isMobile) {
                height = jQuery(window).height();
                height = height * 5;
            }
            console.log("height ::: " + height);
            jQuery('#iframe_skybox_checkout').attr('height', height);
        });
    </script>
    <?php
// ----- Rogged -----
else:
    Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::getUrl("checkout/onepage"));
endif;
// ----- ----- -----
?>
<script>
    setTimeout(function(){
        var location_pathname = window.location.pathname.split('/');
        var skx_bar = document.getElementsByClassName('skx-bar-text');
        console.log("location_pathname::::", location_pathname);
        try{
            if(location_pathname[2] === "international") skx_bar[0].style.display = "none";
        }
        catch(e) {

        }
    }, 300);

</script>