<?php
/** @var Skybox_International_Helper_Data $_helper */
$_helper = Mage::helper('skyboxinternational/data');

if ($_helper->getActive()) {

    /** @var Skybox_Core_Model_Config $_config */
    $_config = Mage::getModel('skyboxcore/config');

    /** @var Skybox_Checkout_Model_Api_Checkout $_checkout */
    $_checkout = Mage::getModel('skyboxcheckout/api_checkout');

    /** @var Skybox_Core_Helper_Allow $allowHelper */
    $allowHelper = Mage::helper('skyboxcore/allow');

    $_cartDataURL = "";
    $_merchant = $_helper->getMerchantCode();
    $template = "";
    $cartId = $_helper->getCartId();
    $cssVersion = $_helper->getCssVersion();

    $_checkout->InitializeBarSkybox();

    $change_country = false;

//    $request = $this->getRequest();
//    $module = $request->getModuleName();
//    $controller = $request->getControllerName();
//    $action = $request->getActionName();
    $getHomeUrl = Mage::helper('core/url')->getHomeUrl();
    $urlCheckCart = Mage::getUrl("checkout/cart");

    $cart = $_config->getSession()->getCartSkybox();

    // Load CSS & JS
    $skybox_url = $_helper->getSkyboxUrlMain();// $_config->skyboxDefaultUrl;
    $api_css_button_international = $skybox_url . 'widgets/api-button/css/api-button-international-css.ashx';
    $api_css_button_international .= '?s=' . $_merchant;
    $api_css_button_international .= '&CssVersion=' . $cssVersion;
    $api_js_button_international = $skybox_url . 'Content/debug/API/js/api-button-tooltip.js';
    $countryChange = 0;

    if ($allowHelper->isCartBarEnabled()) :
        $countryChange = 1;
        $template = '';
//        $cart = $_config->getSession()->getCartSkybox();
        if (!empty($cart)) :
            $template = $cart->BarHtmlTemplate;
            foreach ($cart as $key => $value) :
                $template = str_ireplace('{' . $key . '}', $value, $template);
            endforeach;
        endif;
        $_cartDataURL = $cart->CartDataURL;
        echo $template;
    endif;

    if ($allowHelper->isChangeCountryEnabled()):
//        $cart = $_config->getSession()->getCartSkybox();
        $template = "<div class='main-container' style='padding: 10px 0 0;text-align: right;'>";
        $template .= "<div class='change_country'>";
        $template .= "<a class='skx_position_option_country' href='javascript:;'>Change country</a>";
        $template .= "</div>";
        $template .= "</div>";
        $change_country = true;
        $countryChange = 0;
        $_cartDataURL = $cart->CartDataURL;
        echo $template;
    endif;

    if ($allowHelper->isPriceEnabled()) {
        $productConfigurable = $this->getSkinUrl('js/skybox/catalog.product.configurable.js');
        echo '<script type="text/javascript" src="' . $productConfigurable . '"></script>';
    }

    $skyBoxUrlClientBase = $_helper->getSkyBoxUrlAPI();
    $storeCode = Mage::getModel('skyboxcatalog/api_product')->getStoreCode();
    $skyBoxUrlClientGet = str_ireplace("apirest/", "", $skyBoxUrlClientBase);
    $skyBoxUrlClient = $skyBoxUrlClientGet . "multiplecalculate/" . $storeCode . "/calc-";
    ?>

    <link rel="stylesheet" type="text/css" href="<?php echo $api_css_button_international; ?>"/>
    <link rel="stylesheet" type="text/css"
          href="<?php echo $this->getSkinUrl('css/skybox/style.css?v=' . $cssVersion); ?>"/>
    <script type="text/javascript">
        var URL_CHECK_CART = "<?php echo $urlCheckCart ?>";
        var CART_ID = "<?php echo $cartId ?>";
        var CART_DATA_URL_SKYBOX = "<?php echo $_cartDataURL ?>";
        var MERCHANT_ID_SKYBOX = "<?php echo $_merchant ?>";
        var SKYBOX_URL = "<?php echo $skybox_url ?>";
        var CHANGE_COUNTRY = "<?php echo $change_country ?>";
        var ACTUAL_URI = "<?php echo 'http://' . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . $_SERVER['REQUEST_URI'] ?>";
        var GET_HOME_URL = "<?php echo $getHomeUrl ?>";
        var COUNTRY_CHANGE = "<?php echo $countryChange?>";
        var IS_SKYBOX_VISIBLE = "<?php echo $_checkout->getLocationAllow(); ?>";
        var URL_BASE_MAGENTO = "<?php echo Mage::getBaseUrl() ?>";
        var IS_REGISTRATION_DISABLED_SKYBOX = 1;
        var LOADING_IMAGE = "<?php echo $this->getSkinUrl('images/skybox/ajax-loading.gif')?>";

        (function ($) {
            $(document).ready(function () {
                if (typeof $.fancybox !== "function") {
                    var fileref = document.createElement("link");
                    fileref.rel = "stylesheet";
                    fileref.type = "text/css";
                    fileref.href = "<?php echo $this->getSkinUrl('css/skybox/jquery.fancybox.css');?>";
                    document.getElementsByTagName("head")[0].appendChild(fileref);
                    $('head').append($('<script />').attr('src', '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'js/skybox/jquery.fancybox.js'; ?>'));
                }
                $(".skybox-price-set").each(function (index) {
                    var SkyBoxUrlClient = "<?php echo $skyBoxUrlClient;?>";
                    var dataId = $(this).attr("id");
                    var id = $(this).attr("product-id");
                    var url = SkyBoxUrlClient + id + ".html";
                    var content = $.get(url, function (data) {
                        $("#" + dataId).html(data);
                    });
                });
            });
        })(jQuery);
    </script>
    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'js/skybox/main.js'; ?>"></script>
    <script type="text/javascript">
        //<![CDATA[
        var SKYBOX_OPTIONS_PRICE_URL = '<?php echo Mage::getUrl("skbcheckout/calculate"); ?>';
        //]]>
    </script>
    <script type="text/javascript" src="<?php echo $api_js_button_international; ?>"></script>
    <script>
        // @todo Fix more Change countries Block issue
        setTimeout(function () {
            jQuery("a[href='#'].skx-bar-other").attr('href', 'javascript:;');
            var country_change = "<?php echo $countryChange?>";
            if (parseInt(country_change) === 1) {
                var currencyISO_ = document.getElementsByClassName('skx_banner_label_currencyISO');
                if (currencyISO_.length > 1) {
                    var nextSiblingOne = currencyISO_[0].nextElementSibling;
                    var getAttrNextSiblingOne = nextSiblingOne.getAttribute('class');
                    var nextSiblingLast = currencyISO_[1].nextElementSibling;
                    nextSiblingLast.setAttribute('class', getAttrNextSiblingOne);
                    currencyISO_[1].innerHTML = currencyISO_[0].innerHTML;
                }
            } else {
                var optCountry = document.getElementsByClassName('skx_position_option_country');
                if (optCountry.length > 1) {
                    optCountry[1].innerHTML = optCountry[0].innerText;
                    try {
                        document.getElementById('l_checkout_view_account').style.display = 'none';
                    } catch (e) {

                    }
                }
            }
        }, 500);
    </script>
    <?php
// }
// /? />

    $size = 0; // Calculate height

    if ($allowHelper->getLocationAllow()) {

        $UserTemporal = "1";
        $cartItemCount = 0;

        $cart = $_config->getSession()->getCartSkybox();
        if (!empty($cart)) :
            $UserTemporal = $cart->{'UserTemporal'};
            $CartItemCount = intval($cart->{'CartItemCount'});
            for ($i = 0; $i <= $CartItemCount; $i++) :
                $size = $size + 60;
            endfor;
        endif;

        $merchant = $_helper->getMerchantCode();
        $storeId = $_helper->getStoreId();
        $cartId = $_helper->getCartId();
        $guid = $_checkout->getGuidApi();
        $urlSuccess = Mage::getUrl("skbcheckout/international/success");
        $urlConfirm = Mage::getUrl("skbcheckout/international");
        $token = $_checkout->getAuthorizedToken();

        // Build Iframe
        $url = $_helper->getSkyboxUrlMain() . "WebForms/Checkout/APICheckout.aspx"; //$_config->skyboxDefaultUrl . "WebForms/Checkout/APICheckout.aspx";
        $url .= "?token=" . $token;
        $url .= "&GuiId=" . $guid;
        $url .= "&merchant=" . $merchant;
        $url .= "&idCart=" . $cartId;
        $url .= "&idStore=" . $storeId;
        $url .= "&UrlC=" . $urlConfirm;// "http://magento.skynet.com/magento192/skbcheckout/international";
        $url .= "&paypal=" . $_GET["paypal"];
        $url .= '&checkout=' . strip_tags(Mage::app()->getRequest()->getParam('checkout', ''));
        $url .= "&UrlR=" . $urlSuccess;

        $height = (($UserTemporal == "1") ? 2000 : 1500) + $size;
        // $height = 2500;
    }
}
?>

<div class="div_iframe_skybox_checkout">
    <iframe id="iframe_skybox_checkout" src="<?php echo $url; ?>" frameborder="0" scrolling="no"></iframe>
</div>

<script type="text/javascript">
    jQuery(document).ready(function () {
        var height = <?php echo $height; ?>;
        var size = <?php echo $size; ?>;
        var isMobile = /Mobi/.test(navigator.userAgent);
        console.log("isMobile ::: " + isMobile);
        console.log("size ::: " + size);
        console.log("height ::: " + height);
        if (isMobile) {
            height = jQuery(window).height();
            height = (height * 5) - (size/2);
        }
        var height = height + "px";
        console.log("height (mobile) ::: " + height);
        jQuery('#iframe_skybox_checkout').attr('height', height);
        jQuery('#iframe_skybox_checkout').css('height', height);
    });
</script>
